openapi: 3.0.0
info:
  title: TODO API
  description: API REST para gerenciamento de tarefas
  version: 1.0.0
  contact:
    name: TODO API Support
    email: support@todoapi.com

servers:
  - url: http://localhost:8080/todo-api
    description: Servidor de desenvolvimento

paths:
  /api/tasks:
    get:
      summary: Listar todas as tarefas
      description: Retorna uma lista de todas as tarefas
      tags:
        - Tasks
      responses:
        '200':
          description: Lista de tarefas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Criar nova tarefa
      description: Cria uma nova tarefa no sistema
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        '201':
          description: Tarefa criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{id}:
    get:
      summary: Buscar tarefa por ID
      description: Retorna uma tarefa específica pelo ID
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da tarefa
      responses:
        '200':
          description: Tarefa encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tarefa não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Atualizar tarefa
      description: Atualiza uma tarefa existente
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        '200':
          description: Tarefa atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tarefa não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Excluir tarefa
      description: Exclui uma tarefa do sistema
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da tarefa
      responses:
        '204':
          description: Tarefa excluída com sucesso
        '404':
          description: Tarefa não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{id}/status:
    patch:
      summary: Atualizar status da tarefa
      description: Atualiza apenas o status de uma tarefa
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID da tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusUpdateRequest'
      responses:
        '200':
          description: Status atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Status inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Tarefa não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /tasks/batchUpdateStatus:
    post:
      summary: Atualizar status de múltiplas tarefas
      description: Atualiza o status de várias tarefas em lote
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchStatusUpdateRequest'
      responses:
        '200':
          description: Tarefas atualizadas com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchUpdateResponse'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único da tarefa
        title:
          type: string
          maxLength: 255
          description: Título da tarefa
        description:
          type: string
          maxLength: 1000
          nullable: true
          description: Descrição da tarefa
        status:
          $ref: '#/components/schemas/TaskStatus'
        priority:
          $ref: '#/components/schemas/TaskPriority'
        dateCreated:
          type: string
          format: date-time
          description: Data de criação
        lastUpdated:
          type: string
          format: date-time
          description: Data da última atualização
      required:
        - id
        - title
        - status
        - priority
        - dateCreated
        - lastUpdated

    TaskStatus:
      type: string
      enum:
        - PENDING
        - COMPLETED
      description: Status da tarefa

    TaskPriority:
      type: string
      enum:
        - LOW
        - MEDIUM
        - HIGH
      description: Prioridade da tarefa

    TaskCreateRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          description: Título da tarefa
        description:
          type: string
          maxLength: 1000
          description: Descrição da tarefa
        priority:
          $ref: '#/components/schemas/TaskPriority'
      required:
        - title

    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 255
          description: Título da tarefa
        description:
          type: string
          maxLength: 1000
          description: Descrição da tarefa
        status:
          $ref: '#/components/schemas/TaskStatus'
        priority:
          $ref: '#/components/schemas/TaskPriority'

    StatusUpdateRequest:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/TaskStatus'
      required:
        - status

    BatchStatusUpdateRequest:
      type: object
      properties:
        taskIds:
          type: array
          items:
            type: integer
            format: int64
          description: Lista de IDs das tarefas
        newStatus:
          $ref: '#/components/schemas/TaskStatus'
      required:
        - taskIds
        - newStatus

    BatchUpdateResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Indica se a operação foi bem-sucedida
        message:
          type: string
          description: Mensagem de resultado
      required:
        - success
        - message

    Error:
      type: object
      properties:
        error:
          type: string
          description: Mensagem de erro
      required:
        - error
